apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Web.Plugs.SetLocale, "en")
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", Web do
    pipe_through(:browser)

    get("/", PageController, :index)
  end

  scope "/fdsnws/event/1", Web do
    pipe_through(:browser)

    get("/", FDSNEventController, :base)
    get("/query", FDSNEventController, :query)
    get("/application.wadl", FDSNEventController, :wadl)
    get("/catalogs", FDSNEventController, :catalogs)
    get("/contributors", FDSNEventController, :contributors)
    get("/version", FDSNEventController, :version)
  end

  scope "/:locale", Web do
    pipe_through(:browser)

    get("/", PageController, :index, as: :index_with_locale)

    scope "/actors" do
      get("/", PageController, :actors)
    end

    get("/dashboards/:zone_slug", PageController, :dashboard)

    get("/pages/:page_slug", PageController, :page)

    get("/about", PageController, :about)
    get("/webservices", PageController, :webservices)
    get("/contact", PageController, :contact)
    get("/:zone_slug", PageController, :zone)
    get("/:zone_slug/stations", PageController, :zone_stations)

    scope "/events" do
      get("/search", EventController, :search)
      get("/search/results", EventController, :search_results)
      get("/:event_id", EventController, :show)
    end

    scope "/testimony", as: :testimony do
      get("/new", TestimonyController, :new)
      get("/new/address", TestimonyController, :witness_address)
      get("/:testimony_key", QuestionController, :question)

      post("/new/address", TestimonyController, :witness_address)
      post("/:testimony_key", QuestionController, :form_proceed)
      post("/:testimony_key/next_question", QuestionController, :next_question)
    end
  end
end

apps/web/lib/web/templates/page/about.html.eex
<%
projects = [
%{name: "Bulma", url: "https://bulma.io/"},
%{name: "Font Awesome", url: "https://fontawesome.com/"},
%{name: "Elixir", url: "https://elixir-lang.org/"},
%{name: "Phoenix Framework", url: "https://phoenixframework.org/"},
%{name: "PostgreSQL", url: "https://www.postgresql.org/"}
]
%>
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>"><%= gettext "Home" %></a></li>
        <li class="is-active"><a href="#"><%= gettext "About" %></a></li>
      </ul>
    </nav>
    <div class="content">
      <h1>Namazu</h1>
      <h1>Based on Open Source project</h1>
      <table class="table is-striped">
        <thead>
          <tr>
            <th><%= gettext "Project name" %></th></th>
            <th><%= gettext "Official website" %></th></th>
          </tr>
        </thead>
        <tbody>
        <%= for project <- projects do %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.url |> link(to: project.url) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

apps/web/lib/web/templates/page/actors.html.eex
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>"><%= gettext "Home" %></a></li>
        <li class="is-active"><a href="#"><%= gettext "Actors" %></a></li>
      </ul>
    </nav>
    <div class="content">
      <table class="table is-striped">
        <thead>
          <tr>
            <th></th>
            <th><%= gettext "Name" %></th></th>
            <th><%= gettext "Official website" %></th></th>
          </tr>
        </thead>
        <tbody>
          <%= for actor <- @actors do %>
          <tr>
            <td><%= country_flag(@conn, actor.country_iso2) %></td>
            <td><%= actor.name %></td>
            <td><%= actor.url |> link(to: actor.url) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

apps/web/lib/web/templates/page/contact.html.eex
<%= if @contact_address_latitude do %>
<div style="height: 400px;" class="has-background-link" id="map-address"></div>
<% end %>
<section class="section">
  <div class="container">
    <%# <nav class="breadcrumb" aria-label="breadcrumbs"> %>
    <%#   <ul> %>
    <%#     <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %1>"><%= gettext "Home" %1></a></li> %>
    <%#     <li class="is-active"><a href="#"><%= gettext "Contact" %1></a></li> %>
    <%#   </ul> %>
    <%# </nav> %>
    <nav class="level">
    <%= if @contact_email do %>
    <%= Web.Bulma.level_item(gettext("Email"), @contact_email |> link(to: "mailto:#{@contact_email}")) %>
    <% end %>
    <%= if @contact_phone do %>
    <%= Web.Bulma.level_item(gettext("Phone number"), @contact_phone |> link(to: "tel:#{@contact_phone}")) %>
    <% end %>
    <%= if @contact_address do %>
    <%= Web.Bulma.level_item(gettext("Address"), @contact_address |> markdown()) %>
    <% end %>
    </nav>
  </div>
</section>
<%= if @contact_address_latitude do %>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', (event) => {
    var coordinates = [<%= @contact_address_latitude %>, <%= @contact_address_longitude %>]
    var map = L.map('map-address', {
      center: coordinates,
      keyboard: false,
      dragging: true,
      zoomControl: false,
      boxZoom: false,
      scrollWheelZoom: false,
      doubleClickZoom: true,
      tap: false,
      touchZoom: false,
      zoom: 16,
      maxZoom: 18
    })

    <%# L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', { %>
    <%#   attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors', %>
    <%#   subdomains: 'abcd', %>
    <%#   minZoom: 0, %>
    <%#   maxZoom: 20, %>
    <%#   ext: 'png' %>
    <%# }).addTo(map) %>

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map)

    <%# L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', { %>
    <%#   attribution: 'Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012' %>
    <%# }).addTo(map) %>

    <%# L.tileLayer('https://maps.heigit.org/openmapsurfer/tiles/roads/webmercator/{z}/{x}/{y}.png', { %>
    <%#   maxZoom: 19, %>
    <%#   attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> | Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' %>
    <%# }).addTo(map) %>

    L.marker(coordinates).addTo(map)
    L.control.zoom({position: 'topright'}).addTo(map)
  })
</script>
<% end %>

apps/web/lib/web/templates/page/dashboard.html.eex
<div class="columns is-marginless">
  <div class="column is-narrow">
    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <div style="width: 180px;">
            <img src="<%= Routes.static_path(@conn, "/images/logo-bcsf-renass.svg") %>">
          </div>
        </a>
      </div>
      <div class="navbar-menu">
        <div class="navbar-start">
          <span class="navbar-item is-size-4"><b><%= @zone.name %></b></span>
        </div>
      </div>
    </nav>
    <table class="table is-narrow is-striped">
      <thead>
        <tr>
          <th>Status</th>
          <th>ID</th>
          <th>Date</th>
          <th>Time</th>
          <th>Mag.</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        <%= for event <- @events do %>
        <%
          translated_event_type =
          if event.event_type do
            Gettext.dgettext(Web.Gettext, "event_types", event.event_type) |> String.capitalize()
          else
            Gettext.dgettext(Web.Gettext, "event_types", "event") |> String.capitalize()
          end
        %>
        <tr>
          <td><%= automatic_icon(event.preferred_origin.automatic) %></td>
          <td><%= event.id %></td>
          <td><%= format_date(event.preferred_origin.time, @locale) %></td>
          <td><%= format_time(event.preferred_origin.time, false) %></td>
          <td><b><%= event.preferred_magnitude.magnitude  |> format_magnitude() %></b></td>
          <td><%= translated_event_type %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
  <div id="dashboard-map" class="column">

  </div>
</div>
<script src="<%= Routes.static_path(@conn, "/js/events.js") %>"></script>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', (event) => {
    <% x_center = (@zone.minimal_longitude + @zone.maximal_longitude) / 2 %>
    <% y_center = (@zone.minimal_latitude + @zone.maximal_latitude) / 2 %>
    EventMap('dashboard-map', <%= x_center %>, <%= y_center %>)
      .addMagnitudeLegend()
      .fitBounds(<%= @zone.minimal_longitude %>, <%= @zone.minimal_latitude %>, <%= @zone.maximal_longitude %>, <%= @zone.maximal_latitude %>)
      <%= for event <- @events do %>
      .addEvent(<%= event.preferred_origin.longitude %>, <%= event.preferred_origin.latitude %>, <%= event.preferred_magnitude.magnitude %>, '<%= Routes.event_path(@conn, :show, @locale, event.id) %>')
      <% end %>
  })
</script>

apps/web/lib/web/templates/page/index.html.eex
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <div class="column content has-text-justified is-half">
        <%= Namazu.get_site_description() |> markdown() %>
      </div>
      <%= for zone <- @zones do %>
      <div class="column is-half">
        <div class="card">
          <header style="height: 250px;" class="card-reader has-background-link" id="map-zone-id-<%= zone.id %>"></header>
          <div class="card-content">
            <div class="media-content">
              <p class="title"><%= zone.name |> link(to: Routes.page_path(@conn,:zone, @locale, zone.slug)) %></p>
              <p class="subtitle">
                <hr>
                <div class="content has-text-justified"><%= zone.description |> Web.Filters.markdown() %></div>
              </p>
            </div>
          </div>
          <%# <footer class="card-footer"> %>
          <%#   <a class="card-footer-item" href="<%= Routes.page_path(@conn,:zone, @locale, zone.slug) %1>"> %>
          <%#     <strong><%= gettext "Learn more" %1></strong> %>
          <%#   </a> %>
          <%# </footer> %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>
<script src="<%= Routes.static_path(@conn, "/js/events.js") %>"></script>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', (event) => {
    <%= for zone <- @zones do %>
      <% x_center = (zone.minimal_longitude + zone.maximal_longitude) / 2 %>
      <% y_center = (zone.minimal_latitude + zone.maximal_latitude) / 2 %>
      EventMap('map-zone-id-<%= zone.id %>', <%= x_center %>, <%= y_center %>)
        .addZoomControl()
        <%# .clickUrl('<%= Routes.page_path(@conn,:zone, @locale, zone.slug) %1>') %>
        .fitBounds(<%= zone.minimal_longitude %>, <%= zone.minimal_latitude %>, <%= zone.maximal_longitude %>, <%= zone.maximal_latitude %>)
        <%= for event <- zone.events do %>
        .addEvent(<%= event.preferred_origin.longitude %>, <%= event.preferred_origin.latitude %>, <%= event.preferred_magnitude.magnitude %>, '<%= Routes.event_path(@conn, :show, @locale, event.id) %>', '<%= Web.Filters.event_description(event) %>')
        <% end %>
    <% end %>
  })
</script>

apps/web/lib/web/templates/page/page.html.eex
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>"><%= gettext "Home" %></a></li>
        <li class="is-active"><a href="#"><%= @page.title %></a></li>
      </ul>
    </nav>
    <div class="content">
      <%= @page.content |> Web.Filters.markdown() %>
    </div>
  </div>
</section>

apps/web/lib/web/templates/page/webservices.html.eex
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>"><%= gettext "Home" %></a></li>
        <li class="is-active"><a href="#"><%= gettext "Webservices" %></a></li>
      </ul>
    </nav>
    <div class="content">

      <%= gettext "Work in progress" %>

    </div>
  </div>
</section>

apps/web/lib/web/templates/page/zone.html.eex
<div style="height: 400px;" class="has-background-link" id="map-zone-<%= @zone.slug %>"></div>
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>"><%= gettext "Home" %></a></li>
        <li class="is-active"><a href="#"><%= @zone.name %></a></li>
      </ul>
    </nav>
    <div class="columns is-multiline">
      <div class="column">
        <%= if Map.has_key?(@event_groups, :other_events) do %>
        <div id="tabs-with-content">
          <div class="tabs is-boxed is-medium">
            <ul>
              <li>
                <a><%= gettext "Earthquakes and automatic events" %></a>
              </li>
              <li>
                <a><%= gettext "Other events" %></a>
              </li>
            </ul>
          </div>
          <div>
            <section class="tab-content is-active">
              <%= events_table(@conn, @locale, @event_groups |> Map.get(:earthquakes_and_automatic_events), @events_count, @events_limit, gettext("Next events"), gettext("Previous events")) %>
            </section>
            <section class="tab-content is-active">
              <%= events_table(@conn, @locale, @event_groups |> Map.get(:other_events), @events_count, @events_limit, gettext("Next events"), gettext("Previous events")) %>
            </section>
          </div>
        </div>
        <% else %>
          <%= events_table(@conn, @locale, Map.get(@event_groups, :earthquakes_and_automatic_events), @events_count, @events_limit, gettext("Next events"), gettext("Previous events")) %>
        <% end %>
      </div>
      <div class="column">
        <div class="content">
          <h1><%= @zone.name %></h1>
          <%= if @zone.introduction do %>
            <%= @zone.introduction |> Web.Filters.markdown() %>
          <% end %>
          <div class="message is-link">
            <div class="message-body has-text-black">
              <p><%= gettext "You can participate to science by bringing your testimony." %></p>
              <a class="button is-fullwidth" href="http://www.franceseisme.fr/formulaire/index.php?IdSei=0">
                <span class="icon">
                  <i class="fas fa-pen-alt"></i>
                </span>
                <span>
                  <%= gettext "Have you felt an earthquake ?" %><%= gettext "Testify !" %>
                </span>
              </a>
            </div>
          </div>
          <div class="message is-primary">
            <div class="message-body has-text-black">
              <p>
                <%= gettext "We use many stations to locate events." %>
                <%= gettext "You can look the current state of the network." %>
              </p>
              <a class="button is-fullwidth" href="<%= Routes.page_path(@conn,:zone_stations, @locale, @zone.slug) %>">
                <span class="icon">
                  <i class="fas fa-project-diagram"></i>
                </span>
                <span>
                  <%= gettext "See the stations map" %>
                </span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="<%= Routes.static_path(@conn, "/js/events.js") %>"></script>
<script src="<%= Routes.static_path(@conn, "/js/tabs.js") %>"></script>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', (event) => {
    <% x_center = (@zone.minimal_longitude + @zone.maximal_longitude) / 2 %>
    <% y_center = (@zone.minimal_latitude + @zone.maximal_latitude) / 2 %>
    EventMap('map-zone-<%= @zone.slug %>', <%= x_center %>, <%= y_center %>)
      .addZoomControl()
      .addMagnitudeLegend()
      .fitBounds(<%= @zone.minimal_longitude %>, <%= @zone.minimal_latitude %>, <%= @zone.maximal_longitude %>, <%= @zone.maximal_latitude %>)
      <%= for event <- Map.get(@event_groups, :earthquakes_and_automatic_events) do %>
        .addEvent(<%= event.preferred_origin.longitude %>, <%= event.preferred_origin.latitude %>, <%= event.preferred_magnitude.magnitude %>, '<%= Routes.event_path(@conn, :show, @locale, event.id) %>', '<%= Web.Filters.event_description(event) %>')
      <% end %>
      <%= for event <- Map.get(@event_groups, :other_events, []) do %>
        .addEvent(<%= event.preferred_origin.longitude %>, <%= event.preferred_origin.latitude %>, <%= event.preferred_magnitude.magnitude %>, '<%= Routes.event_path(@conn, :show, @locale, event.id) %>', '<%= Web.Filters.event_description(event) %>')
      <% end %>

    Tabs('tabs-with-content')
  })
</script>

apps/web/lib/web/templates/page/zone_stations.html.eex
<div style="height: 800px;" class="has-background-link" id="map-stations" %>"></div>
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<%= Routes.index_with_locale_path(@conn, :index, @locale) %>">Home</a></li>
        <%= if @zone do %><li><a href="<%= Routes.page_path(@conn,:zone, @locale, @zone.slug) %>"><%= @zone.name %></a></li><% end %>
        <li class="is-active"><a href="#"><%= @title %></a></li>
      </ul>
    </nav>
    <div class="content">
      <h1><%= @zone.name %></h1>

      <div class="columns is-multiline">
        <%= for stations_chunk <- @stations_chunked_by_network do %>
        <%
          network = stations_chunk |> List.first() |> Map.get(:network)
          stations_count = length(stations_chunk)
        %>
        <div class="column is-half">
          <div class="box">
            <h2 class="title"><%= ngettext "Network %{network}", "Network %{network} (%{stations_count} stations)", stations_count, network: network.network_code, stations_count: stations_count %></h2>
            <h3 class="subtitle is-4"><%= network.description %></h3>
            <hr class="is-marginless" style="height: 5px; background-color: <%= network.color %>;">
            <div style="max-height: 200px; overflow-y: auto;">
              <table class="table is-fullwidth is-hoverable is-stripped is-narrow">
                <thead>
                  <tr>
                    <th>Station code</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                  </tr>
                </thead>
                <tbody>
                  <%= for station <- stations_chunk do %>
                    <% current_period = List.first(station.periods) %>
                    <tr>
                      <th><%= station.station_code %></th>
                      <td><%= current_period.latitude |> Web.Filters.format_two_digits() %></td>
                      <td><%= current_period.longitude |> Web.Filters.format_two_digits() %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<script src="<%= Routes.static_path(@conn, "/js/events.js") %>"></script>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', (event) => {
    map = EventMap('map-stations', 3, 45)
      .fitBounds(<%= @minimal_longitude %>, <%= @minimal_latitude %>, <%= @maximal_longitude %>, <%= @maximal_latitude %>)
      .addZoomControl()
<%= for stations_chunk <- @stations_chunked_by_network do %>
  <%= for station <- stations_chunk do %>
      <% current_period = List.first(station.periods) %>
  .addStation(<%= current_period.longitude %>, <%= current_period.latitude %>, '<%= station.network.color %>','<%= "#{station.network.network_code}.#{station.station_code}" %>')
  <% end %>
<% end %>
  })
</script>