apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Web.Plugs.SetLocale, "en")
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", Web do
    pipe_through(:browser)

    get("/", PageController, :index)
  end

  scope "/fdsnws/event/1", Web do
    pipe_through(:browser)

    get("/", FDSNEventController, :base)
    get("/query", FDSNEventController, :query)
    get("/application.wadl", FDSNEventController, :wadl)
    get("/catalogs", FDSNEventController, :catalogs)
    get("/contributors", FDSNEventController, :contributors)
    get("/version", FDSNEventController, :version)
  end

  scope "/:locale", Web do
    pipe_through(:browser)

    get("/", PageController, :index, as: :index_with_locale)

    scope "/actors" do
      get("/", PageController, :actors)
    end

    get("/dashboards/:zone_slug", PageController, :dashboard)

    get("/pages/:page_slug", PageController, :page)

    get("/about", PageController, :about)
    get("/webservices", PageController, :webservices)
    get("/contact", PageController, :contact)
    get("/:zone_slug", PageController, :zone)
    get("/:zone_slug/stations", PageController, :zone_stations)

    scope "/events" do
      get("/search", EventController, :search)
      get("/search/results", EventController, :search_results)
      get("/:event_id", EventController, :show)
    end

    scope "/testimony", as: :testimony do
      get("/new", TestimonyController, :new)
      get("/new/address", TestimonyController, :witness_address)
      get("/:testimony_key", QuestionController, :question)

      post("/new/address", TestimonyController, :witness_address)
      post("/:testimony_key", QuestionController, :form_proceed)
      post("/:testimony_key/next_question", QuestionController, :next_question)
    end
  end
end

apps/web/lib/web/controllers/fdsn_event_controller.ex
defmodule Web.FDSNEventController do
  import Plug.Conn

  alias Namazu.Seismic
  alias Namazu.Repo
  import Ecto.Query

  use Web, :controller

  @version 1.2

  # "catalog",
  # "contributor",
  # "updateafter"

  def parse_datetime(_datetime = ""), do: nil
  def parse_datetime(_datetime = nil), do: nil

  def parse_datetime(datetime) do
    case DateTime.from_iso8601(datetime) do
      {:ok, datetime, _offset} ->
        datetime

      {:error, :missing_offset} ->
        {:ok, datetime, _offset} = DateTime.from_iso8601(datetime <> "Z")
        datetime
    end
  end

  def parse_float(_value = ""), do: nil
  def parse_float(_value = nil), do: nil

  def parse_float(value) do
    {value, _} = Float.parse(value)
    value
  end

  def parse_integer(_value = ""), do: nil
  def parse_integer(_value = nil), do: nil

  def parse_integer(value), do: String.to_integer(value)

  def parse_event_types(_event_types = ""), do: nil
  def parse_event_types(_event_types = nil), do: nil

  def parse_event_types(event_types) do
    String.split(event_types, ",")
    |> Enum.map(&Namazu.Seismic.Event.quakeml_to_namazu_event_type(&1))
  end

  def parse_order_by(_value = ""), do: nil
  def parse_order_by(_value = nil), do: nil

  def parse_order_by(value) do
    case value do
      "time" -> :descending_time
      "time-asc" -> :ascending_time
      "magnitude" -> :descending_magnitude
      "magnitude-asc" -> :ascending_magnitude
      "ascending_time" -> :ascending_time
      "descending_time" -> :descending_time
      "ascending_magnitude" -> :ascending_magnitude
      "descending_magnitude" -> :descending_magnitude
      _ -> nil
    end
  end

  def fdsn_event_query(params) do
    Namazu.Search.EventSearch.query(%Namazu.Search.EventSearch{
      start_time: Map.get(params, "starttime") |> parse_datetime(),
      end_time: Map.get(params, "endtime") |> parse_datetime(),
      minimal_longitude: Map.get(params, "minlongitude") |> parse_float(),
      maximal_longitude: Map.get(params, "maxlongitude") |> parse_float(),
      minimal_latitude: Map.get(params, "minlatitude") |> parse_float(),
      maximal_latitude: Map.get(params, "maxlatitude") |> parse_float(),
      minimal_magnitude: Map.get(params, "minmagnitude") |> parse_float(),
      maximal_magnitude: Map.get(params, "maxmagnitude") |> parse_float(),
      minimal_depth: Map.get(params, "mindepth") |> parse_float(),
      maximal_depth: Map.get(params, "maxdepth") |> parse_float(),
      event_types: Map.get(params, "eventtype") |> parse_event_types(),
      event_id: Map.get(params, "eventid"),
      limit: Map.get(params, "limit") |> parse_integer(),
      offset: Map.get(params, "offset") |> parse_integer(),
      order_by: Map.get(params, "orderby") |> parse_order_by()
    })
  end

  def get_event_ids_chunks(params, chunk_size \\ 100) do
    fdsn_event_query(params)
    |> Repo.all()
    |> Enum.map(fn e -> e.id end)
    |> Enum.chunk_every(chunk_size)
  end

  def get_events_from_ids(event_ids) do
    Seismic.event_query()
    |> where([event: e], e.id in ^event_ids)
  end

  def sort_events_chunk(events, params) do
    case Map.get(params, "orderby") do
      "time" ->
        events |> Enum.sort_by(fn e -> e.preferred_origin.time end) |> Enum.reverse()

      "time-asc" ->
        events |> Enum.sort_by(fn e -> e.preferred_origin.time end)

      "magnitude" ->
        events |> Enum.sort_by(fn e -> e.preferred_magnitude.magnitude end) |> Enum.reverse()

      "magnitude-asc" ->
        events |> Enum.sort_by(fn e -> e.preferred_magnitude.magnitude end)

      _ ->
        events
    end
  end

  def query(conn, params) do
    format = Map.get(params, "format", "xml")

    case format do
      "json" ->
        features =
          fdsn_event_query(params)
          |> Seismic.preload_distinctive_cities()
          |> Repo.all()
          |> Enum.map(fn e ->
            %{
              id: e.id,
              geometry: %{
                coordinates: [
                  e.preferred_origin.longitude,
                  e.preferred_origin.latitude,
                  -e.preferred_origin.depth
                ],
                type: "Point"
              },
              properties: %{
                description: Web.Filters.event_description(e),
                automatic: e.preferred_origin.automatic,
                mag: e.preferred_magnitude.magnitude,
                magType: e.preferred_magnitude.magnitude_type,
                # place: "TODO!!!",
                time: e.preferred_origin.time,
                type: e.event_type,
                url: Routes.event_url(conn, :show, "en", e.id)
              },
              type: "Feature"
            }
          end)

        json(conn, %{
          type: "FeatureCollection",
          features: features
        })

      "text" ->
        conn =
          conn
          |> put_resp_content_type("text/plain")
          |> send_chunked(:ok)

        for chunk <- get_event_ids_chunks(params) do
          events =
            get_events_from_ids(chunk)
            |> Seismic.preload_preferred()
            |> Repo.all()
            |> sort_events_chunk(params)

          text = Phoenix.View.render(Web.FDSNEventView, "query.txt", events: events)

          chunk(conn, text)
        end

        conn

      _ ->
        include_all_origins = Map.get(params, "includeallorigins", "false") == "true"
        include_all_magnitudes = Map.get(params, "includeallmagnitudes", "false") == "true"
        include_arrivals = Map.get(params, "includearrivals", "false") == "true"

        conn =
          conn
          |> put_layout(:none)
          |> put_resp_content_type("application/xml")
          |> send_chunked(:ok)

        escaped_url = Phoenix.Controller.current_url(conn, params) |> String.replace("&", "&amp;")

        chunk(
          conn,
          Phoenix.View.render(Web.FDSNEventView, "query_start.xml", url: escaped_url)
        )

        for chunk <- get_event_ids_chunks(params) do
          events_query =
            get_events_from_ids(chunk)
            |> Seismic.preload_origins(!(include_all_origins || include_all_magnitudes))
            |> Seismic.preload_magnitudes(!(include_all_origins || include_all_magnitudes))

          events_query =
            if Map.has_key?(params, "orderby") do
              Seismic.preload_preferred(events_query)
            else
              events_query
            end

          events =
            if include_arrivals do
              Seismic.preload_origins_arrivals(events_query)
            else
              events_query
            end
            |> Repo.all()
            |> sort_events_chunk(params)

          xml =
            Phoenix.View.render(Web.FDSNEventView, "query.xml",
              events: events,
              include_all_origins: include_all_origins,
              include_all_magnitudes: include_all_magnitudes,
              include_arrivals: include_arrivals
            )

          chunk(conn, xml)
        end

        chunk(conn, Phoenix.View.render(Web.FDSNEventView, "query_end.xml", %{}))

        conn
    end
  end

  def base(conn, _params) do
    text(conn, "base")
  end

  def wadl(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("application.wadl", version: @version)
  end

  def catalogs(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("catalog.xml")
  end

  def contributors(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("contributors.xml")
  end

  def version(conn, _params) do
    text(conn, @version)
  end
end

apps/web/lib/web/views/fdsn_event_view.ex
defmodule Web.FDSNEventView do
  use Web, :view
  import Web.Filters
end

apps/web/lib/web/templates/fdsn_event/application.wadl.eex
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<application xmlns="http://wadl.dev.java.net/2009/02">
  <doc title="FDSN event web service <%= @version %>"/>
  <resources base="<%= Routes.fdsn_event_url(@conn, :base) %>">
    <resource path="/">
      <method id="index" name="GET">
        <response>
          <representation mediaType="text/plain"/>
          <representation mediaType="application/xml"/>
        </response>
      </method>
      <resource path="/query">
        <method id="query" name="GET">
          <request>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="starttime" style="query" type="xs:date">
              <doc xml:lang="english" title="limit to events occurring on or after the specified start time" />
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="endtime" style="query" type="xs:date">
              <doc xml:lang="english" title="limit to events occurring on or before the specified end time"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minlatitude" style="query" type="xs:double">
              <doc xml:lang="english" title="southern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxlatitude" style="query" type="xs:double">
              <doc xml:lang="english" title="northern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minlongitude" style="query" type="xs:double">
              <doc xml:lang="english" title="western boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxlongitude" style="query" type="xs:double">
              <doc xml:lang="english" title="eastern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minmagnitude" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with a magnitude larger than or equal to the specified minimum"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxmagnitude" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with a magnitude smaller than or equal to the specified maximum"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="magnitudetype" style="query" type="xs:string">
              <doc xml:lang="english" title="type of Magnitude used to test minimum and maximum limits (case insensitive)" />
            </param>
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="catalog" style="query" type="xs:string" default="NEIC+PDE"> -->
            <!--   <doc xml:lang="english" title="Specify the catalog from which origins and magnitudes will be retrieved"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="contributor" style="query" type="xs:string"> -->
            <!--   <doc xml:lang="english" title="Limit to events contributed by a specified contributor"/> -->
            <!-- </param> -->
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxdepth" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with depths equal to or less than the specified depth"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="mindepth" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with depths equal to or greater than the specified depth"/>
            </param>
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="latitude" style="query" type="xs:double" default="0.0"> -->
            <!--   <doc xml:lang="english" title="Specify the central latitude point for a radial search"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="longitude" style="query" type="xs:double" default="0.0"> -->
            <!--   <doc xml:lang="english" title="Specify the central longitude point for a radial search"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxradius" style="query" type="xs:double" default="180.0"> -->
            <!--   <doc xml:lang="english" title="Specify maximum distance from the geographic point defined by latitude and longitude"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minradius" style="query" type="xs:double" default="0.0"> -->
            <!--   <doc xml:lang="english" title="Specify minimum distance from the geographic point defined by latitude and longitude"/> -->
            <!-- </param> -->
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="orderby" style="query" type="xs:string" default="time">
              <doc xml:lang="english" title="Specify the ordering of the returned results"/>
              <option value="time">
                <doc xml:lang="english" title="Sort by time, descending"/>
              </option>
              <option value="magnitude">
                <doc xml:lang="english" title="Sort by magnitude, descending"/>
              </option>
              <option value="time-asc">
                <doc xml:lang="english" title="Sort by time, ascending"/>
              </option>
              <option value="magnitude-asc">
                <doc xml:lang="english" title="Sort by magnitude, ascending"/>
              </option>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="updatedafter" style="query" type="xs:date">
              <doc xml:lang="english" title="Limit to events updated after the specified time"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="eventid" style="query" type="xs:string">
              <doc xml:lang="english" title="Retrieve an event based on the unique ID"/>
            </param>
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includearrivals" style="query" type="xs:boolean" default="false"> -->
            <!--   <doc xml:lang="english" title="Specify if phase arrivals should be included"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includeallmagnitudes" style="query" type="xs:boolean" default="false"> -->
            <!--   <doc xml:lang="english" title="Retrieve all magnitudes for the event, or only the primary magnitude from within the catalog"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includeallorigins" style="query" type="xs:boolean" default="false"> -->
            <!--   <doc xml:lang="english" title="Retrieve all origins or only the primary origin associated with each event in a catalog"/> -->
            <!-- </param> -->
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="limit" style="query" type="xs:int">
              <doc xml:lang="english" title="Limit the results to the specified number of events"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="offset" style="query" type="xs:int">
              <doc xml:lang="english" title="Return results starting at the event count specified"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="format" style="query" type="xs:string" default="xml">
              <doc xml:lang="english" title="Specify output format"/>
              <option value="xml" mediaType="application/xml"/>
              <option value="text" mediaType="text/plain"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="nodata" style="query" type="xs:int" default="204">
              <doc xml:lang="english" title="Specify which HTML Status code is returned when no data is found."/>
              <option value="204"/>
              <option value="404"/>
            </param>
          </request>
          <response>
            <representation mediaType="text/plain"/>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="/version">
        <method id="version" name="GET">
          <response>
            <representation mediaType="text/plain"/>
          </response>
        </method>
      </resource>
      <resource path="/catalogs">
        <method id="catalogs" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="/contributors">
        <method id="contributors" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
    </resource>
  </resources>
</application>

apps/web/lib/web/templates/fdsn_event/catalog.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<Catalogs>
  <total>1</total>
  <Catalog>BCSF-RENASS</Catalog>
</Catalogs>

apps/web/lib/web/templates/fdsn_event/contributors.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<Contributors>
  <Contributor>BCSF-RENASS</Contributor>
</Contributors>

apps/web/lib/web/templates/fdsn_event/query.txt.eex
<%= for event <- @events do %>
  <%= event.id %>|<%= event.preferred_origin.time |> DateTime.to_iso8601() %>|<%= event.preferred_origin.latitude %>|<%= event.preferred_origin.longitude %>|<%= event.preferred_origin.depth %>|Namazu|Namazu|<%= event.id %>|<%= event.preferred_magnitude.magnitude_type %>|<%= event.preferred_magnitude.magnitude %>|Namazu|World
<% end %>

apps/web/lib/web/templates/fdsn_event/query.xml.eex
<%= for event <- @events do %>
<event publicID="smi:namazu/event/<%= event.id %>">
  <preferredOriginID>smi:namazu/origin/<%= event.preferred_origin_id %></preferredOriginID>
  <preferredMagnitudeID>smi:namazu/magnitude/<%= event.preferred_magnitude_id %></preferredMagnitudeID>
  <type><%= Namazu.Seismic.Event.namazu_to_quakeml_event_type(event.event_type) %></type>
  <%= for origin <- event.origins do %>
<%= if origin.id == event.preferred_origin_id || @include_all_origins do %>
  <origin publicID="smi:namazu/origin/<%= origin.id %>">
    <time>
      <value><%= origin.time |> DateTime.to_iso8601() %></value>
      <%= if origin.time_uncertainty do %>
      <uncertainty><%= origin.time_uncertainty %></uncertainty>
      <% end %>
    </time>
    <latitude>
      <value><%= origin.latitude %></value>
      <%= if origin.latitude_uncertainty do %>
        <uncertainty><%= origin.latitude_uncertainty %></uncertainty>
      <% end %>
    </latitude>
    <longitude>
      <value><%= origin.longitude %></value>
      <%= if origin.longitude_uncertainty do %>
        <uncertainty><%= origin.longitude_uncertainty %></uncertainty>
      <% end %>
    </longitude>
    <depth>
      <value><%= origin.depth %></value>
      <%= if origin.depth_uncertainty do %>
      <uncertainty><%= origin.depth_uncertainty %></uncertainty>
      <% end %>
    </depth>
    <depthType><%= origin.depth_type %></depthType>
    <%= if origin.method_id do %>
    <methodID><%= origin.method_id %></methodID>
    <% end %>
    <%= if origin.earthmodel_id do %>
    <earthModelID><%= origin.earthmodel_id %></earthModelID>
    <% end %>
    <type><%= origin.origin_type %></type>
    <%= if origin.evaluation_status do %>
    <evaluationStatus><%= origin.evaluation_status %></evaluationStatus>
    <% end %>
    <evaluationMode><%= if origin.automatic do %>automatic<% else %>manual<% end %></evaluationMode>
    <%= if @include_arrivals do %>
      <%= for arrival <- origin.arrivals do %>
      <arrival publicID="smi:namazu/arrival/<%= arrival.id %>">
        <pickID>smi:namazu/pick/<%= arrival.pick_id %></pickID>
        <phase><%= arrival.phase_code %></phase>
        <%= if arrival.azimuth do %>
        <azimuth><%= arrival.azimuth %></azimuth>
        <% end %>
        <%= if arrival.distance do %>
        <distance><%= arrival.distance %></distance>
        <% end %>
        <%= if arrival.time_residual do %>
        <timeResidual><%= arrival.time_residual %></timeResidual>
        <% end %>
        <%= if arrival.time_weight do %>
        <timeWeight><%= arrival.time_weight %></timeWeight>
        <% end %>
      </arrival>
      <% end %>
    <% end %> <%# arrivals %>
  </origin>
<% end %>
  <%= for magnitude <- origin.magnitudes do %>
<%= if magnitude.id == event.preferred_magnitude_id || @include_all_magnitudes do %>
  <magnitude publicID="smi:namazu/magnitude/<%= magnitude.id %>">
    <mag>
      <value><%= magnitude.magnitude %></value>
      <%= if magnitude.magnitude_uncertainty do %>
      <uncertainty><%= magnitude.magnitude_uncertainty %></uncertainty>
      <% end %>
    </mag>
    <type><%= magnitude.magnitude_type %></type>
    <originID>smi:namazu/origin/<%= origin.id %></originID>
    <%= if magnitude.method_id do %>
    <methodID><%= magnitude.method_id %></methodID>
    <% end %>
    <%= if magnitude.station_count do %>
    <stationCount><%= magnitude.station_count %></stationCount>
    <% end %>
    <%= if magnitude.evaluation_status do %>
    <evaluationStatus><%= magnitude.evaluation_status %></evaluationStatus>
    <% end %>
  </magnitude>
<% end %>
  <% end %><%# magnitudes %>
  <% end %><%# origins %>
<%= if @include_arrivals do %>
  <%= for pick <- deduplicate_picks(event) do %>
  <pick publicID="smi:namazu/pick/<%= pick.id %>">
    <time>
      <value><%= pick.time |> DateTime.to_iso8601() %></value>
    </time>
    <%= if pick.filter_id do %>
    <filterID><%= pick.filter_id %></filterID>
    <% end %>
    <%= if pick.method_id do %>
    <methodID><%= pick.method_id %></methodID>
    <% end %>
    <phaseHint><%= pick.phase_hint_code %></phaseHint>
    <%= if pick.polarity do %>
    <polarity><%= pick.polarity %></polarity>
    <% end %>
    <waveformID networkCode="<%= pick.stream.network_code %>" stationCode="<%= pick.stream.station_code %>" locationCode="<%= pick.stream.location_code %>" channelCode="<%= pick.stream.channel_code %>">smi:namazu/stream/<%= pick.stream.id %></waveformID>
    <evaluationMode><%= if pick.automatic do %>automatic<% else %>manual<% end %></evaluationMode>
  </pick>
  <% end %>
<% end %><%# picks %>
</event>
<% end %><%# events %>

apps/web/lib/web/templates/fdsn_event/query_end.xml.eex
</eventParameters>
</q:quakeml>

apps/web/lib/web/templates/fdsn_event/query_start.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<q:quakeml xmlns:q="http://quakeml.org/xmlns/quakeml/1.2" xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://quakeml.org/schema/xsd http://quakeml.org/schema/xsd/QuakeML-1.2.xsd">
  <eventParameters publicID="smi:<%= @url %>">